name: Execution of tests

on:
    pull_request:
      branches: [ main ]

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3

      - name: install dependencies
        uses: npm install

      - name: run libryTests
        run: npx LibryTemplateTest run

      - name: run expectedValuesLibryTests
        run: npx ExpectedValuesLibryTest run